### ISSUE TITLE
Terminology: prerequisites section still needs work

### ISSUE THREAD

**Issue by dcmiddle** [confidential-computing/governance#125]
The [pre-req section] (https://github.com/confidential-computing/governance/blob/main/terminology/common-terminology.md#package-deployability-prerequisites) has a mix of package requirements and platform or TEE requirements.

i.e. firmware evidence and certificate hygiene are aspects of attestation and the TEE whereas a TLS library is something you might include in a package or depend on from the platform. 

I believe the intent of the section is captured in the sentence "... define a minimal set of functional prerequisites which a deployable instance of the package must incorporate."

If this is the case we should refocus the section on things that must be present in the package. It may be the case that this list cannot be generated in a general way; i.e. a VM must provide a TLS library but a process can be dynamically linked with a library provided in the operating system.

**Comment by PenglinYang** [comment]
In my personal opinion, minimal set of functional prerequisites have the following components:

- Secure channel implementation, e.g. TLS library. (One question: in the confidential process, if the TLS library is outisde the CC environmnet, how to make sure the secure channel is point-to-point between TEE and server. In another word, if the TLS client or the library is outside the CC enviroment, the "secure channel" can only prove it posseses the CC environment, but cannot prove the secure channel is inside the CC environment.)
- Certificate, which is used for authentication and authorization.
- Remote attestation mechanism, e.g. quote enclave in SGX, secure processor in SEV-SNP.
- TA provisioning agent, which is used in the opening provision stage of CC environment. (While this components may not necessary because some UA could call for TEE resource directly.)
