### ISSUE TITLE
Create a document around GitHub process and propose at a TAC conference call

### ISSUE THREAD

**Issue by cetola** [confidential-computing/governance#27]
See the minutes for details on the process.

**Comment by spjohnso** [comment]
Which set of minutes?

Also I don't see this as being the right long-term solution, as we modify the process how will this be recorded, and referenced?

**Comment by cetola** [comment]
Sorry, I need to dig through the minutes to log in which set we put forth a process for working on GitHub (i.e. the fact that we require two members approval before merging a change to a TAC document).

If the document that comes from that search exists here in GitHub would that not track the changes adequately?

**Comment by spjohnso** [comment]
You could say that of anything we've discussed at the TAC.

How will I find this info... currently I would have to search the issues to find this thread (once it's closed) to find the pointer to the right set of minutes.

Each time the processes are updated the minutes would have to spell out in full the process.. otherwise you're off looking at different sets of minutes.

Discussion around the changes are not change controlled.

**Comment by cetola** [comment]
Okay, let's discuss this in the TAC meeting tomorrow. This issue was me following up on an action item, so I'm happy to amend, or better yet remove that action item. 👍

**Comment by dthaler** [comment]
Feb 20, 2020 minutes contain the initial discussion, where minutes have:
"c. We need to propose a vote for allowing merges on GitHub being allowed if enough votes are collected through that system. d. In general, we should have a document that details the GitHub process. "

Mar 19, 2020 minutes contain an addition to this action item regarding pull requests:
"Note to the GitHub Process: If there are no comments in 1 week, we will mark these as approved. "

**Comment by cetola** [comment]
Also from Feb 6, 2020:
"We should use issues for things that do not have pull requests. We should make use of date-based tags for versions that we consider 'known good states' for documents. We need 2 approvers for merging pull requests."

So this gives us:
1. Use issues for any action items that do not have pull requests.
2. Pull requests require 2 (voting member?) approvers before being merged.
3. After 1 week with no comments on a pull request it will be considered approved and merged.

Does this accurately reflect what folks think, and if so, shall I simply add these instructions to the README? (seems silly to have an entire document for this unless folks plan to elaborate)

Also, I feel like #2 and #3 on that list are in conflict with each other.

**Comment by dcmiddle** [comment]
Consider alternate wording to address the conflict btwn 2&3:
1. PRs require 2 TAC approvers unaffiliated with the submitter and no changes requested to the commit.
2. PRs should not be merged for a minimum of 1 calendar week to provide opportunity for all TAC members to review.

The spirit of the policy is to allow a meaningful and diverse review. The policy doesn't obviate other TAC action, i.e. should something commit and there later turns out to be dissent, the TAC can still revert the commit or otherwise address the issue.

(In github the policy itself is configurable as a branch protection:
https://help.github.com/en/github/administering-a-repository/about-required-reviews-for-pull-requests)

**Comment by spjohnso** [comment]
We did also discuss the creation of "Timebomb" label so that you could easily identify which issues are now on the clock. The process should note that items need to be labelled.

**Comment by dthaler** [comment]
Here's the process that I think we are using in practice right now:
•	The chair checks the issues and PRs to decide which ones (if any) should be on the next meeting agenda
•	All TAC members should have sent their github ids to the chair and Stephano so any TAC PRs can add all TAC members as reviewers
•	Once PRs are approved by two TAC members (including the author, if a TAC member) with no change requests from any other reviewers, then a “time bomb” label is added with a timeout of 1 week.
•	An issue is merged once it’s been open for at least a week and either the “time bomb” has been there for a week, or two TAC members other than the author approve, with no change requests from any other reviewers.

**Comment by cetola** [comment]
Added in new document: https://github.com/confidential-computing/governance/commit/caff9b580261077718447f982b7673e9c96fdac3
