### ISSUE TITLE
Progression Policy: Define what a growth plan entails

### ISSUE THREAD

**Issue by spjohnso** [confidential-computing/governance#50]
The [progression policy](https://github.com/confidential-computing/governance/blob/master/project-progression-policy.md) in incubation and graduation stages refers to a 'growth plan' but it does not define what's expected in said plan.

**Comment by spjohnso** [comment]
During TAC call we formally agreed that Growth Plan would require identification of Security Policy from Sandbox->Incubation stages

**Comment by AevaOnline** [comment]
OpenStack introduced the idea of project "incubation" and "graduation" in 2012, which has since been followed by CNCF and other organizations.

A brief history of that can be found here - https://docs.openstack.org/project-team-guide/introduction.html

Two years later, the OpenStack TC instituted "project reform", also known as "the big tent", declaring an end to the graduation review process and taking a loose position that any project which follows the four open principles of openstack - and wanted to be part of the OpenStackFoundation - could be.

https://governance.openstack.org/tc/resolutions/20141202-project-structure-reform-spec.html

This in turn resulted in a project status dashboard with many qualitative measurements summarized to display the subjective maturity of each project. This subjective maturity rating was eventually removed, in favor of specific qualitative bars, such as "does the project have a Vulnerability Management Team that works with the OSF's VMT?"

https://www.openstack.org/software/project-navigator/openstack-components#openstack-services

**Comment by AevaOnline** [comment]
The CNCF has followed a similar paradigm, providing a "landscape" view of all projects which interactively displays similar qualitative and quantitative measurements. The CNCF chose to integrate their dashboard with additional aggregated data, combining project stats (# of contributors, commit frequency) and information about the company behind a given project (funding status / market cap, employee count, links to social media accounts)

https://landscape.cncf.io/

The CNCF defines its process for project growth here: https://github.com/cncf/toc/tree/master/process

with specific graduation criteria here: https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc

**Comment by AevaOnline** [comment]
To add additional context for the above comments:

In the TAC meeting today a call for comparables was put forth, and I offered to provide references to the two foundations I have previously been a part of. Each of those (OSF, CNCF) addressed specific challenges through the creation of these governance processes -- challenges which may or may not be applicable to the CCC. We can learn from them, but should not necessarily follow the same paradigms.

I suggest for a next step that the TAC discuss whether or not we would want to adopt qualitative evaluations of projects, such as (but not necessarily the same as) those described in the section here, and that a proposal of such a list be created for discussion.
https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#graduation-stage

In particular, I suggest we consider the burden of time placed upon the TAC should such a process be defined, the impact to projects should the TAC not have sufficient time to adequately review all incoming requests, and the impact that any subjective definition of quality will have upon projects. 

As they say, "you get what you measure"; what ever the TAC adopts as graduation criteria may become specific targets which many projects will diligently seek to demonstrate.

**Comment by dthaler** [comment]
https://github.com/openenclave/openenclave/pull/3448 is an example growth plan writeup that is based on the text in the project progression policy, and the initial Open Enclave presentation that Mike Brasher did to the TAC in October 2019 which included an initial "plan" that the TAC accepted as being sufficient to meet the Incubation stage criteria.

**Comment by dthaler** [comment]
Closing now that PR 69 is merged
